### ISSUE TITLE
Existing gem hacking, not working gem or no usable documentation.

### ISSUE THREAD

**Issue by Val** [lydianblues/jstree-rails#1]
Hello,

Did you know there was an existing gem with the same name (https://github.com/tristanm/jstree-rails) ?

For now using gem "jstree-rails" without any version take your instead of the previous one.
The bad is that your version of jstree-rails does not work for me and i cannot find any good documentation for your gem (lots of Todo...)

Regards.

**Comment by lydianblues** [comment]
There was no pre-existing gem on rubygems with that name.  My version uses jstree at version 1.0, which is probably why it doesn't work for you.  The API is different from prerelease-3.  The gem itself includes some docs in the docs directory at the root level.

Good luck,
Michael
